[env]
platform = espressif32
board = esp32-s3-n16r8-dashboard
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0

lib_deps =
  lovyan03/LovyanGFX@^1.1.16
  bblanchon/ArduinoJson@^7.2.1

[env:esp32-s3-n16r8-dashboard]

[env:lcd-smoke-st7796]
build_flags =
  -DLCD_SMOKE_TEST

[env:lcd-smoke-ili9488]
build_flags =
  -DLCD_SMOKE_TEST
  -DLCD_PANEL_ILI9488

[env:lcd-smoke-ili9486]
build_flags =
  -DLCD_SMOKE_TEST
  -DLCD_PANEL_ILI9486
